sudo: required
language: java
jdk:
- oraclejdk8
script:
- mvn clean install -Dmaven.compiler.target=1.8 -Dmaven.compiler.source=1.8
- mvn clean verify
before_install:
  - curl https://www.jpm4j.org/install/script | sh
  - jpm install com.codacy:codacy-coverage-reporter:assembly
  - export CODACY_PROJECT_TOKEN=9420f5dfa0b84a9b83fcaab2b8cac9d7
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)

after_success:
  - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml