sudo: required
language: java
jdk:
- oraclejdk8
script:
- mvn clean install -Dmaven.compiler.target=1.8 -Dmaven.compiler.source=1.8
- mvn clean verify
before_install:
- sudo apt-get install jq
- wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)
after_success:
- mvn clean test jacoco:report coveralls:report
- coveralls
- java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml