before_install:
  - curl -sL https://github.com/jpm4j/jpm4j.installers/raw/master/dist/biz.aQute.jpm.run.jar >jpm4j.jar
  - java -jar jpm4j.jar -u init
  - ~/jpm/bin/jpm install com.codacy:codacy-coverage-reporter:assembly
language: java
sudo: required
jdk:
  - oraclejdk8
script:
- mvn clean install -Dmaven.compiler.target=1.8 -Dmaven.compiler.source=1.8
- mvn clean verify
after_success:
  - ~/jpm/bin/codacy-coverage-reporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml
